version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/desktop"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    labels: ["dependencies", "desktop"]
    commit-message:
      prefix: "Зависимости (desktop)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    labels: ["dependencies", "ci"]
    commit-message:
      prefix: "Зависимости (actions)"
